opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil

disabled_rules:
  - trailing_whitespace

excluded:
  - Pods
  - .build
  - DerivedData

line_length:
  warning: 120
  error: 200

identifier_name:
  min_length: 2
  max_length: 40
